### ISSUE TITLE
errors when running xjc

### ISSUE THREAD

**Issue by hagaisela** [Siggen/jaxb-namespace-prefix#1]
I am trying to run this plugin with xjc and I am getting multiple errors like this one:
[ERROR] Unsupported binding namespace "http://jaxb2-commons.dev.java.net/namespace-prefix". Perhaps you meant "http://jaxb.dev.java.net/plugin/code-injector"?
  line 6 of file:/home/hagai/opensource/webex/webex-java-sdk/schema/src/main/resources/com/webex/schemas/2002/06/service/history/history.xsd

This is my bindings file:
<?xml version="1.0"?>
<jxb:bindings version="1.0"
    xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:namespace="http://jaxb2-commons.dev.java.net/namespace-prefix"
    xsi:schemaLocation="http://java.sun.com/xml/ns/jaxb http://java.sun.com/xml/ns/jaxb/bindingschema_2_0.xsd
    http://jaxb2-commons.dev.java.net/namespace-prefix http://java.net/projects/jaxb2-commons/sources/svn/content/namespace-prefix/trunk/src/main/resources/prefix-namespace-schema.xsd">

```
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/common/common.xsd">
    <jxb:bindings>
        <namespace:prefix name="com" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/service.xsd">
    <jxb:bindings>
        <namespace:prefix name="serv" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/attendee/attendee.xsd">
    <jxb:bindings>
        <namespace:prefix name="att" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/ep/ep.xsd">
    <jxb:bindings>
        <namespace:prefix name="ep" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/event/event.xsd">
    <jxb:bindings>
        <namespace:prefix name="event" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/history/history.xsd">
    <jxb:bindings>
        <namespace:prefix name="history" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/meeting/meeting.xsd">
    <jxb:bindings>
        <namespace:prefix name="meet" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/meeting/teleconferenceonly.xsd">
    <jxb:bindings>
        <namespace:prefix name="auo" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/meetingtype/meetingtype.xsd">
    <jxb:bindings>
        <namespace:prefix name="mtgtype" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/sales/sales.xsd">
    <jxb:bindings>
        <namespace:prefix name="sales" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/session/session.xsd">
    <jxb:bindings>
        <namespace:prefix name="sess" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/meetingtype/meetingtype.xsd">
    <jxb:bindings>
        <namespace:prefix name="mtgtype" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/sales/sales.xsd">
    <jxb:bindings>
        <namespace:prefix name="sales" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/session/session.xsd">
    <jxb:bindings>
        <namespace:prefix name="sess" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/supportsession/supportsession.xsd">
    <jxb:bindings>
        <namespace:prefix name="sc" />
    </jxb:bindings>
</jxb:bindings>    
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/training/training_ims_qtiasiv1p2.xsd">
    <jxb:bindings>
        <namespace:prefix name="qtiasi" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/training/training_ims_qtiresv1p2.xsd">
    <jxb:bindings>
        <namespace:prefix name="qti" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/training/trainingsession.xsd">
    <jxb:bindings>
        <namespace:prefix name="train" />
    </jxb:bindings>
</jxb:bindings>
<jxb:bindings schemaLocation="com/webex/schemas/2002/06/service/user/user.xsd">
    <jxb:bindings>
        <namespace:prefix name="use" />
    </jxb:bindings>
</jxb:bindings>    
```

/jxb:bindings

**Comment by Siggen** [comment]
Hi,

I don't know for sure what is happening here, the binding definition I'm using is similar to yours. I noticed you're still using the schema location at java.net (which isn't available anymore), could you try to update it to:

```
<?xml version="1.0"?>
    <jxb:bindings version="1.0"
                  xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xmlns:namespace="http://jaxb2-commons.dev.java.net/namespace-prefix"
                  xsi:schemaLocation="http://java.sun.com/xml/ns/jaxb http://java.sun.com/xml/ns/jaxb/bindingschema_2_0.xsd
                  http://jaxb2-commons.dev.java.net/namespace-prefix https://raw.githubusercontent.com/Siggen/jaxb2-namespace-prefix/master/src/main/resources/prefix-namespace-schema.xsd">
```

... and try again ?

**Comment by MikeEdgar** [comment]
In case it helps, I noticed that the 'unsupported binding namespace' may occur if the `-Xnamespace-prefix` argument is not passed to xjc.

**Comment by Siggen** [comment]
Thanks @MikeEdgar ! @hagaisela, could you check that you did specify the `-Xnamespace-prefix` argument in your plugin config:

    <plugin>
        <groupId>org.jvnet.jaxb2.maven2</groupId>
        <artifactId>maven-jaxb2-plugin</artifactId>
        <version>0.8.0</version>
        <configuration>
            <schemaDirectory>src/main/resources</schemaDirectory>
            <catalog>src/main/resources/catalog.xml</catalog>
            <schemaIncludes>
                <include>*.xsd</include>
            </schemaIncludes>
            <bindingDirectory>src/main/resources</bindingDirectory>
            <bindingIncludes>
                <include>bindings.xml</include>
            </bindingIncludes>
            <args>
                <arg>-extension</arg>
                <arg>-Xnamespace-prefix</arg>
            </args>
        </configuration>
        <executions>
            <execution>
                <goals>
                    <goal>generate</goal>
                </goals>
            </execution>
        </executions>
        <dependencies>
            <dependency>
                <groupId>org.jvnet.jaxb2_commons</groupId>
                <artifactId>jaxb2-namespace-prefix</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </plugin>

**Comment by Siggen** [comment]
No answer for two months, I guess the issue is resolved. Closed.
