### ISSUE TITLE
No prefix annotations are set when an XSD defines only elements

### ISSUE THREAD

**Issue by solind** [Siggen/jaxb-namespace-prefix#3]
This plugin relies on the getUriCountMap field to enumerate referenced namespaces in an XSD, however, if an XSD contains only element definitions (and no type definitions) in some targetNamespace, that targetNamespace will have exactly zero URI counts -- and the plugin will skip adding the annotations to the package-info class.

I'd fix this, but all these com.sun classes look pretty obscure, and I don't know how to obtain the targetNamespace from them.  Any ideas?

**Comment by solind** [comment]
Here, I updated the plugin to scrape the package's ObjectFactory methods for namespace annotations, and return those in addition to the URI counts (attached).  This should solve the problem.

[NamespacePrefixPlugin.java.txt](https://github.com/Siggen/jaxb2-namespace-prefix/files/731802/NamespacePrefixPlugin.java.txt)

**Comment by Siggen** [comment]
Thank you for your input (and I'm sorry for the late answer, I've been busy lately) ! 

I usually don't use XSDs with only elements definitions, so I've never encountered that case. Good catch. 

I commented on your PR, let me known. Thanks, regards.

**Comment by Siggen** [comment]
I merged your PR, I'll make a release shortly. Thanks !

**Comment by Siggen** [comment]
Version 1.3 is available online: https://oss.sonatype.org/#nexus-search;quick~jaxb2-namespace-prefix
