### ISSUE TITLE
Support for JakartaEE

### ISSUE THREAD

**Issue by gituserDoesNotExist** [Siggen/jaxb-namespace-prefix#7]
Hey,

we are currently migrating to the new Jakarta dependencies:

https://wiki.eclipse.org/Jakarta_EE_Maven_Coordinates

Therefore we can no longer use the classes

javax.xml.bind.annotation.XmlSchema
and
javax.xml.bind.annotation.XmlNs

Can you update the Plugin to support the new Jakarta-Namespace

jakarta.xml.bind.annotation.XmlNs
and
jakarta.xml.bind.annotation.XmlNs

??

Best regards

**Comment by Siggen** [comment]
A new version (2.0-SNAPSHOT) is available here : https://oss.sonatype.org/#nexus-search;quick~jaxb2-namespace-prefix

I don't have any project migrated to jakarta yet, so I could not test it myself. 

Could have a try and tell me if it's good or not ?

**Comment by gituserDoesNotExist** [comment]
Hey,

 

thank you for your reply and the change. I have taken a look at it and it seems to work.

 

Thanks (:


Gesendet: Mittwoch, 08. September 2021 um 18:49 Uhr
Von: "Manuel Siggen" ***@***.***>
An: "Siggen/jaxb2-namespace-prefix" ***@***.***>
Cc: "gituserDoesNotExist" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [Siggen/jaxb2-namespace-prefix] Support for JakartaEE (#7)


 

A new version (2.0-SNAPSHOT) is available here : https://oss.sonatype.org/#nexus-search;quick~jaxb2-namespace-prefix

I don't have any project migrated to jakarta yet, so I could not test it myself.

Could have a try and tell me if it's good or not ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nikkijuk** [comment]
Tested 2.0 snapshot. Worked as it should.  

My problem was that I have 2 versions of same set of schemas, and each set has same target namespace. 

In addition, current (v2) set of schema files contains whole older set (v1) of files without changes, and thus there's nicely file x_v1 for type a and file x_v2 for same type a. 

Creating root elements for v2 and v1 from this set to same directory fails, and if I put them to separate directories (package per schema) generation goes ok but conflict comes when playing with xml as classloader founds duplicates.

I didn't managed to solve my problem yet, but are working on it. Seems to me that this plugin is not solution to me, but I need to do something different.

Just deleting generated duplicated before compile might go, but it feels to me that it's not quite optimal as we're soon having v3 and then v4 and ..

**Comment by kan-izh** [comment]
> Could have a try and tell me if it's good or not ?

I have tried this and works fine as far as I could tell. Thank you!

Could you please release the version so we could use official version rather than relying on snapshots.

**Comment by Siggen** [comment]
> Could you please release the version so we could use official version rather than relying on snapshots.

Version 2.0 has been released : https://oss.sonatype.org/#nexus-search;quick~jaxb2-namespace-prefix. It should be available in maven central soon.
